/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projeto.integrador.pkg2;

import javax.swing.JOptionPane;

/**
 *
 * @author patricia
 */
public class Status extends javax.swing.JFrame {

    /** Creates new form Dados_Aluno */
    public Status() {
        initComponents();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBVoltar_Fis = new javax.swing.JButton();
        jBSim_Soc = new javax.swing.JButton();
        jBSim_Soc1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("COMO VOÇÊ SE SENTE ATUALMENTE?");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 940, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/triste.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, 240, 250));

        jBVoltar_Fis.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBVoltar_Fis.setText("VOLTAR");
        jBVoltar_Fis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBVoltar_Fis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltar_FisActionPerformed(evt);
            }
        });
        getContentPane().add(jBVoltar_Fis, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 560, 100, 30));

        jBSim_Soc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBSim_Soc.setText("TRISTE");
        jBSim_Soc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBSim_Soc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSim_SocActionPerformed(evt);
            }
        });
        getContentPane().add(jBSim_Soc, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 110, 30));

        jBSim_Soc1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBSim_Soc1.setText("ALEGRE");
        jBSim_Soc1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBSim_Soc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSim_Soc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBSim_Soc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/alegre.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 250, 250));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/retroceder.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/avancar.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 90, 40));

        jLabel9.setText("AVANÇAR");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 50, 20));

        jLabel8.setText("RETROCEDER");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, -1, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logotipopequenoo.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/background.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 1180, 620));

        setSize(new java.awt.Dimension(1182, 649));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBVoltar_FisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltar_FisActionPerformed
        Tela_Social soc = new Tela_Social();
        soc.setVisible(true);
    }//GEN-LAST:event_jBVoltar_FisActionPerformed

    private void jBSim_SocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSim_SocActionPerformed
        Tela_Fisico fisico = new Tela_Fisico();
        fisico.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBSim_SocActionPerformed

    private void jBSim_Soc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSim_Soc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSim_Soc1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBSim_Soc;
    private javax.swing.JButton jBSim_Soc1;
    private javax.swing.JButton jBVoltar_Fis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
