/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projeto.integrador.pkg2;

import javax.swing.JOptionPane;

/**
 *
 * @author patricia
 */
public class Tela_Motivos extends javax.swing.JFrame {

    /** Creates new form Dados_Aluno */
    public Tela_Motivos() {
        initComponents();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBMoral = new javax.swing.JButton();
        jBSocial = new javax.swing.JButton();
        jBVirtual = new javax.swing.JButton();
        jBVerbal = new javax.swing.JButton();
        jBPsicologico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBMoral.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBMoral.setText("Moral");
        jBMoral.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jBMoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 140, 30));

        jBSocial.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBSocial.setText("Social");
        jBSocial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jBSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 120, 30));

        jBVirtual.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBVirtual.setText("Virtual");
        jBVirtual.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jBVirtual, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 560, 140, 30));

        jBVerbal.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBVerbal.setText("Verbal");
        jBVerbal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(jBVerbal, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 300, 120, 30));

        jBPsicologico.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jBPsicologico.setText("Psicolôgico");
        jBPsicologico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jBPsicologico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPsicologicoActionPerformed(evt);
            }
        });
        getContentPane().add(jBPsicologico, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 180, 30));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Intimidado ou Ameaçado");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, 200, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Ingnorado ou Excluído");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 590, 210, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Difamado ou Caluniado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 220, 20));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Xingado ou Apelidado");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 330, 200, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Humilhado ou intimidado pela internet");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 590, 310, 20));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel6.setText(" VOCÊ ENCONTRA- SE TRISTE ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 1090, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 32)); // NOI18N
        jLabel8.setText("POR ALGUM DESSES MOTIVOS?");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 520, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/virtual.png"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 240, 200));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/psicologico.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 110, 190));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/SOCIAL.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, 290, 190));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/moral.png"))); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 240, 190));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/xingar.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 90, 240, 200));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/LogoTipoPequeno.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 280, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logotipopequenoo.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/retroceder.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/avancar.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 90, 40));

        jLabel18.setText("AVANÇAR");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 50, 20));

        jLabel19.setText("RETROCEDER");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, -1, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/background.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 1180, 620));

        setSize(new java.awt.Dimension(1182, 649));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBPsicologicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPsicologicoActionPerformed
       
        Tela_Psicologico psi = new Tela_Psicologico();
        psi.setVisible(true);
         String message = "ALGUM DE SEUS COLEGAS LHE TRATA MAL?";
String title = "";
//Exibe caixa de dialogo (veja figura) solicitando confirmação ou não. 
//Se o usuário clicar em "Sim" retorna 0 pra variavel reply, se informado não retorna 1
int reply = JOptionPane.showConfirmDialog(null, message, title, JOptionPane.YES_NO_OPTION);
  if (reply == JOptionPane.YES_OPTION){
//cadastrar resposta
  }if (reply == JOptionPane.NO_OPTION){
//cadastrar resposta
  }
        dispose();
    }//GEN-LAST:event_jBPsicologicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Motivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBMoral;
    private javax.swing.JButton jBPsicologico;
    private javax.swing.JButton jBSocial;
    private javax.swing.JButton jBVerbal;
    private javax.swing.JButton jBVirtual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
