/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projeto.integrador.pkg2;

import javax.swing.JOptionPane;

/**
 *
 * @author patricia
 */
public class Tela_Psicologico extends javax.swing.JFrame {

    /** Creates new form Dados_Aluno */
    public Tela_Psicologico() {
        initComponents();
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jBVoltar_Psi = new javax.swing.JButton();
        jBProximo_Psi1 = new javax.swing.JButton();
        jBSim_Soc = new javax.swing.JButton();
        jBSim_Soc1 = new javax.swing.JButton();
        jBSim_Soc2 = new javax.swing.JButton();
        jBSim_Soc3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel6.setText("POR QUAL DESSES MOTIVO?");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 690, -1));

        jBVoltar_Psi.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBVoltar_Psi.setText("VOLTAR");
        jBVoltar_Psi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBVoltar_Psi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltar_PsiActionPerformed(evt);
            }
        });
        getContentPane().add(jBVoltar_Psi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 510, 100, 30));

        jBProximo_Psi1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBProximo_Psi1.setText("PROXIMO");
        jBProximo_Psi1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBProximo_Psi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProximo_Psi1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBProximo_Psi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 560, 100, 30));

        jBSim_Soc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBSim_Soc.setText("RELIGIOSO");
        jBSim_Soc.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBSim_Soc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSim_SocActionPerformed(evt);
            }
        });
        getContentPane().add(jBSim_Soc, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 310, 110, 30));

        jBSim_Soc1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBSim_Soc1.setText("SEXUAL");
        jBSim_Soc1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBSim_Soc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSim_Soc1ActionPerformed(evt);
            }
        });
        getContentPane().add(jBSim_Soc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 560, 110, 30));

        jBSim_Soc2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBSim_Soc2.setText("PESO");
        jBSim_Soc2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBSim_Soc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSim_Soc2ActionPerformed(evt);
            }
        });
        getContentPane().add(jBSim_Soc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 110, 30));

        jBSim_Soc3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jBSim_Soc3.setText("RACIAL");
        jBSim_Soc3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBSim_Soc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSim_Soc3ActionPerformed(evt);
            }
        });
        getContentPane().add(jBSim_Soc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 110, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/SEXUAL.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 240, 190));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/peso.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 230, 190));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/RACIAL.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 240, 190));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/religioso.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 240, 190));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/LogoTipoPequeno.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 280, 40));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/logotipopequenoo.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/retroceder.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 520, -1, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/avancar.png"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 90, 40));

        jLabel13.setText("AVANÇAR");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 570, 50, 20));

        jLabel14.setText("RETROCEDER");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 570, -1, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/background.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 1180, 620));

        setSize(new java.awt.Dimension(1182, 649));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBProximo_Psi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProximo_Psi1ActionPerformed
       
  dispose();
  
        Tela_Verbal verbal = new Tela_Verbal();
        verbal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBProximo_Psi1ActionPerformed

    private void jBVoltar_PsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltar_PsiActionPerformed
        Tela_Motivos motivos = new Tela_Motivos();
        motivos.setVisible(true);
    }//GEN-LAST:event_jBVoltar_PsiActionPerformed

    private void jBSim_SocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSim_SocActionPerformed
        Tela_Fisico fisico = new Tela_Fisico();
        fisico.setVisible(true);
        dispose();
    }//GEN-LAST:event_jBSim_SocActionPerformed

    private void jBSim_Soc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSim_Soc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSim_Soc1ActionPerformed

    private void jBSim_Soc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSim_Soc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSim_Soc2ActionPerformed

    private void jBSim_Soc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSim_Soc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSim_Soc3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Psicologico().setVisible(true);
            
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBProximo_Psi1;
    private javax.swing.JButton jBSim_Soc;
    private javax.swing.JButton jBSim_Soc1;
    private javax.swing.JButton jBSim_Soc2;
    private javax.swing.JButton jBSim_Soc3;
    private javax.swing.JButton jBVoltar_Psi;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables

}
